/* ---------------------------------------------------------------------------
   MRI 25th Anniversary — the story close-ups
   ---------------------------------------------------------------------------
   One composition per story: which motifs are drawn around its station on the
   survey sheet, and where. Offsets are in plate units relative to the station
   (dx to the right, dy DOWN the sheet — so negative dy is upslope). The window
   is 660 x 440 with the station a little below centre, so keep compositions
   inside roughly dx ±300, dy −230 … +180.

   `m` is a motif name from the motif library; `k` is its scale (a standing
   person is ~22 units at k = 1); `o` is passed through as opts.
   Adjust a story's scene here — nothing else needs to change.
--------------------------------------------------------------------------- */
window.MRI_VIGNETTES_DATA = {
  1: { name: 'Glaciers', items: [
    /* the glacier itself is the hero: the crevasse field sits on the tongue */
    { m: 'crevasseField',    dx:    0, dy:  120, k: 1.0, hero: true, snap: 'glacier' },
    { m: 'seracCliff',       dx:  -40, dy:   70, k: 0.7, snap: 'glacier', rx: 12 },
    { m: 'snowStake',        dx:  -60, dy:  160, k: 0.9, snap: 'glacier', rx: -26 },
    { m: 'surveyTape',       dx:   60, dy:  200, k: 0.9, o: { length: 70 } },
    { m: 'climbersRoped',    dx: -190, dy:  210, k: 0.85 },
    { m: 'theodoliteTripod', dx:  150, dy:  130, k: 0.8, o: { surveyor: true } },
    { m: 'moraineRidge',     dx:   40, dy:  250, k: 0.9 },
  ]},
  2: { name: 'Mountain observation systems', items: [
    { m: 'weatherStation',   dx:    0, dy:  -20, k: 1.5, hero: true },
    { m: 'dataLogger',       dx:   95, dy:   24, k: 1.0 },
    { m: 'satelliteDish',    dx: -115, dy:   12, k: 1.0 },
    { m: 'person',           dx:   58, dy:   62, k: 1.0 },
    { m: 'drone',            dx:  -60, dy: -130, k: 1.0 },
    { m: 'openNotebook',     dx:  140, dy:   74, k: 0.9 },
    { m: 'theodoliteTripod', dx: -180, dy:   64, k: 0.9 },
    { m: 'snowStake',        dx:  200, dy:  -40, k: 0.9 },
  ]},
  3: { name: 'Elevation-dependent warming', items: [
    { m: 'isothermLines',    dx:   10, dy:  -70, k: 1.7, hero: true },
    { m: 'thermometerPost',  dx: -160, dy:  120, k: 1.0 },
    { m: 'thermometerPost',  dx:  -40, dy:   40, k: 1.0 },
    { m: 'thermometerPost',  dx:   95, dy:  -60, k: 1.0 },
    { m: 'weatherStation',   dx:  200, dy:  -20, k: 1.0 },
    { m: 'birdsFlying',      dx: -130, dy: -150, k: 1.0 },
    { m: 'person',           dx: -100, dy:   70, k: 1.0, o: { flip: true } },
  ]},
  4: { name: 'Social dimensions of glacier loss', items: [
    { m: 'memorialCross',    dx:  -25, dy:   32, k: 1.2, hero: true },
    { m: 'childAndElder',    dx:   70, dy:   52, k: 1.05 },
    { m: 'groupInCircle',    dx: -160, dy:   96, k: 0.9 },
    { m: 'moraineRidge',     dx:   30, dy:  -70, k: 1.2 },
    { m: 'mountainLake',     dx:  140, dy:  -40, k: 1.0 },
    { m: 'rockfallBoulders', dx: -120, dy:  -40, k: 0.8 },
  ]},
  5: { name: 'Water towers & downstream dependencies', items: [
    /* one chain, plumbed: fall → reservoir → channel → field → village */
    { m: 'waterfall',        dx:  -60, dy: -150, k: 1.0, hero: true, snap: 'river' },
    { m: 'damWall',          dx:  -40, dy:  -30, k: 0.65, snap: 'river' },
    { m: 'pylonLine',        dx:  120, dy:  -50, k: 0.6, o: { count: 2 } },
    { m: 'irrigationChannel',dx:   20, dy:   70, k: 1.0, snap: 'river', rx: 44 },
    { m: 'cropRows',         dx:  110, dy:  110, k: 0.9 },
    { m: 'womanWithJug',     dx:  -30, dy:  120, k: 0.85 },
    { m: 'houseCluster',     dx:   60, dy:  185, k: 0.75 },
  ]},
  6: { name: 'Ecosystems & nature-based solutions', items: [
    { m: 'plantedSaplings',  dx:  -40, dy:   42, k: 1.2, hero: true },
    { m: 'flowerMeadow',     dx:   85, dy:  -18, k: 1.3 },
    { m: 'beehive',          dx:  160, dy:   24, k: 1.0 },
    { m: 'detailedPine',     dx: -170, dy:  -60, k: 1.0 },
    { m: 'shrubs',           dx:   40, dy:  104, k: 1.0 },
    { m: 'birdsFlying',      dx: -100, dy: -150, k: 1.0 },
    { m: 'farmerWithHoe',    dx: -115, dy:   84, k: 1.0 },
    { m: 'marmot',           dx:  200, dy:  -72, k: 0.9 },
  ]},
  7: { name: 'Forests, soils & carbon dynamics', items: [
    { m: 'soilProfile',      dx:  -95, dy:   64, k: 0.95, hero: true },
    { m: 'rootSystem',       dx:   85, dy:    4, k: 1.2 },
    { m: 'detailedPine',     dx: -185, dy:  -44, k: 1.1 },
    { m: 'loggedStand',      dx:  160, dy:   94, k: 1.0 },
    { m: 'detailedDeciduous',dx:   20, dy: -112, k: 1.0 },
    { m: 'openNotebook',     dx:  -30, dy:  126, k: 0.8 },
  ]},
  8: { name: 'Adaptation & resilience', items: [
    { m: 'houseCluster',     dx:    0, dy:   24, k: 1.1, hero: true },
    { m: 'stoneWall',        dx: -125, dy:   62, k: 1.0, o: { length: 95 } },
    { m: 'debrisFlow',       dx:   60, dy: -145, k: 0.9 },
    { m: 'groupInCircle',    dx:  150, dy:   84, k: 0.9 },
    { m: 'plantedSaplings',  dx: -175, dy:  -40, k: 0.9 },
    { m: 'signpost',         dx:   95, dy:   50, k: 0.9 },
  ]},
  9: { name: 'Cascading hazards & risks', items: [
    /* a cascade with an order: lake → debris flow → flood → the bridge at risk */
    { m: 'glacialLake',      dx:  -70, dy: -150, k: 0.9 },
    { m: 'debrisFlow',       dx:    0, dy:  -20, k: 1.0, hero: true },
    { m: 'floodWave',        dx:   10, dy:  120, k: 1.0, snap: 'river' },
    { m: 'bridge',           dx:   10, dy:  175, k: 0.8, snap: 'river' },
    { m: 'houseCluster',     dx:  120, dy:  200, k: 0.7 },
    { m: 'rockfallBoulders', dx:  160, dy:  -60, k: 0.7 },
  ]},
  10: { name: 'Agriculture & food systems', items: [
    { m: 'terracesWithCrops',dx:  -60, dy:   44, k: 1.4, hero: true },
    { m: 'farmerWithHoe',    dx:   64, dy:   62, k: 1.0 },
    { m: 'goatFlock',        dx:  150, dy:  -20, k: 1.0 },
    { m: 'orchard',          dx: -175, dy:  -50, k: 1.0 },
    { m: 'cropRows',         dx:   95, dy:  132, k: 1.0 },
    { m: 'yak',              dx: -150, dy:  104, k: 0.9 },
    { m: 'alpineHouse',      dx:  170, dy:  104, k: 0.8 },
  ]},
  11: { name: 'Cultural landscapes & heritage', items: [
    { m: 'monastery',        dx:    0, dy:  -20, k: 1.4, hero: true },
    { m: 'stoneWall',        dx: -145, dy:   62, k: 1.0, o: { length: 100 } },
    { m: 'hikerWithStick',   dx:   90, dy:   72, k: 1.0 },
    { m: 'hikerWithStick',   dx:  125, dy:   86, k: 0.95, o: { flip: true } },
    { m: 'terracesWithCrops',dx: -165, dy:  -64, k: 0.9 },
    { m: 'personCarrying',   dx:  -40, dy:  104, k: 1.0 },
    { m: 'stupaOrShrine',    dx:  175, dy:  -62, k: 0.9 },
  ]},
  12: { name: 'Gender & social equity', items: [
    { m: 'womanWithJug',     dx:  -30, dy:   30, k: 1.1, hero: true },
    { m: 'personCarrying',   dx:   50, dy:   42, k: 1.0, o: { flip: true } },
    { m: 'womanWithJug',     dx:  125, dy:   72, k: 1.0, o: { flip: true } },
    { m: 'irrigationChannel',dx: -150, dy:   82, k: 1.0, snap: 'river' },
    { m: 'houseCluster',     dx:  100, dy:  -92, k: 0.9 },
    { m: 'cropRows',         dx: -100, dy:  132, k: 1.0 },
    { m: 'childAndElder',    dx:  185, dy:   12, k: 0.9 },
  ]},
  13: { name: 'Tourism', items: [
    { m: 'cableCar',         dx:  -40, dy:  -70, k: 1.0, hero: true },
    { m: 'alpineHouse',      dx:   40, dy:   70, k: 0.8 },
    { m: 'signpost',         dx:  110, dy:   40, k: 0.8 },
    { m: 'hikerWithStick',   dx:  140, dy:   70, k: 0.7 },
    { m: 'hikerWithStick',   dx:  168, dy:   82, k: 0.7 },
    { m: 'hikerWithStick',   dx:  196, dy:   96, k: 0.7 },
    { m: 'tent',             dx: -170, dy:   60, k: 0.8 },
    { m: 'bus',              dx:   10, dy:  150, k: 0.5 },
  ]},
  14: { name: 'Demographic change & migration', items: [
    { m: 'houseCluster',     dx:  -85, dy:   22, k: 1.1, hero: true },
    { m: 'roadSwitchbacks',  dx:  105, dy:   62, k: 1.1 },
    { m: 'bus',              dx:  155, dy:  132, k: 0.5 },
    { m: 'personCarrying',   dx:   40, dy:   72, k: 1.0 },
    { m: 'hikerWithStick',   dx:   92, dy:  102, k: 1.0 },
    { m: 'childAndElder',    dx: -165, dy:   92, k: 0.9 },
    { m: 'birdsFlying',      dx:   60, dy: -150, k: 1.1 },
    { m: 'signpost',         dx:   20, dy:   30, k: 0.9 },
  ]},
  15: { name: 'Peacebuilding & transboundary cooperation', items: [
    { m: 'braidedRiver',     dx:   30, dy:   44, k: 1.2, snap: 'river' },
    { m: 'bridge',           dx:   40, dy:  -12, k: 1.2, hero: true, snap: 'river' },
    { m: 'borderPost',       dx:  -95, dy:   22, k: 1.1 },
    { m: 'groupInCircle',    dx:  155, dy:   62, k: 0.9 },
    { m: 'fenceLine',        dx: -185, dy:   62, k: 1.0 },
    { m: 'person',           dx: -140, dy:   -6, k: 1.0 },
    { m: 'person',           dx:  120, dy:  -10, k: 1.0, o: { flip: true } },
  ]},
  16: { name: 'Urbanisation & infrastructure', items: [
    { m: 'crane',            dx:  -40, dy:  -30, k: 1.0, hero: true },
    { m: 'houseCluster',     dx:   70, dy:   50, k: 1.0 },
    { m: 'tunnelPortal',     dx: -185, dy:   60, k: 0.9 },
    { m: 'bridge',           dx:   20, dy:  140, k: 0.7, snap: 'river' },
    { m: 'pylonLine',        dx:  170, dy:  -40, k: 0.75, o: { count: 3 } },
    { m: 'bus',              dx: -100, dy:  125, k: 0.5 },
  ]},
  17: { name: 'Indigenous & local knowledge', items: [
    { m: 'shepherd',         dx:    0, dy:   32, k: 1.1, o: { animals: 2 }, hero: true },
    { m: 'yak',              dx:   95, dy:   62, k: 1.0 },
    { m: 'stupaOrShrine',    dx: -125, dy:  -30, k: 1.0 },
    { m: 'childAndElder',    dx:  -60, dy:   92, k: 1.0 },
    { m: 'detailedDeciduous',dx:  145, dy:  -80, k: 1.0 },
    { m: 'flowerMeadow',     dx:   60, dy:  124, k: 1.0 },
    { m: 'beehive',          dx: -180, dy:   64, k: 0.9 },
  ]},
  18: { name: 'Land tenure & mountain governance', items: [
    { m: 'fenceLine',        dx: -150, dy:   42, k: 1.0, o: { length: 120 } },
    { m: 'stoneWall',        dx:   45, dy:   62, k: 1.0 },
    { m: 'groupInCircle',    dx:    0, dy:  -40, k: 1.0, hero: true },
    { m: 'treatyDocument',   dx:  135, dy:  -80, k: 0.9 },
    { m: 'surveyTape',       dx:  -60, dy:  112, k: 1.0, o: { length: 90 } },
    { m: 'theodoliteTripod', dx:   95, dy:   94, k: 0.9, o: { surveyor: true } },
    { m: 'cropRows',         dx: -175, dy:  -60, k: 0.9 },
  ]},
  19: { name: 'Hydropower & energy transitions', items: [
    { m: 'damWall',          dx:  -45, dy:  -60, k: 0.8, hero: true, snap: 'river' },
    { m: 'turbineHouse',     dx:   85, dy:   62, k: 1.1 },
    { m: 'pylonLine',        dx:  175, dy:  -20, k: 0.9, o: { count: 3 } },
    { m: 'braidedRiver',     dx:   40, dy:  142, k: 1.0, snap: 'river' },
    { m: 'person',           dx: -135, dy:   84, k: 0.9 },
    { m: 'waterfall',        dx: -180, dy: -120, k: 0.8, snap: 'river' },
  ]},
  20: { name: 'Mountains in global frameworks', items: [
    { m: 'globe',            dx:    0, dy:  -30, k: 1.4, hero: true },
    { m: 'treatyDocument',   dx:  105, dy:   42, k: 1.0 },
    { m: 'groupInCircle',    dx: -125, dy:   42, k: 0.9 },
    { m: 'openNotebook',     dx:   85, dy:  112, k: 0.8 },
    { m: 'birdsFlying',      dx:  -90, dy: -160, k: 1.0 },
    { m: 'signpost',         dx:  190, dy:  -40, k: 0.9 },
  ]},
  21: { name: 'Legal action & mountain justice', items: [
    { m: 'scalesOfJustice',  dx:  -40, dy:  -30, k: 1.3, hero: true },
    { m: 'gavel',            dx:   85, dy:   32, k: 1.0 },
    { m: 'treatyDocument',   dx: -155, dy:   42, k: 0.9 },
    { m: 'groupInCircle',    dx:  135, dy:   84, k: 0.9 },
    { m: 'detailedDeciduous',dx: -125, dy: -110, k: 1.0 },
    { m: 'mountainLake',     dx:  -40, dy:  124, k: 0.9 },
  ]},
  22: { name: 'Mountains & the arts', items: [
    { m: 'painterAtEasel',   dx:    0, dy:   22, k: 1.3, hero: true },
    { m: 'openNotebook',     dx: -115, dy:   62, k: 0.9 },
    { m: 'person',           dx:  115, dy:   52, k: 1.0 },
    { m: 'birdsFlying',      dx:  -80, dy: -140, k: 1.0 },
    { m: 'detailedPine',     dx:  155, dy:  -62, k: 1.0 },
    { m: 'flowerMeadow',     dx: -165, dy:   92, k: 1.0 },
    { m: 'eagle',            dx:  120, dy: -170, k: 1.0 },
  ]},
  23: { name: 'Future scenarios for mountain regions', items: [
    { m: 'glacialLake',      dx:  -85, dy: -100, k: 1.0 },
    { m: 'snowStake',        dx:   62, dy:  -62, k: 1.0 },
    { m: 'plantedSaplings',  dx:  105, dy:   42, k: 1.0 },
    { m: 'drone',            dx: -135, dy: -160, k: 0.9 },
    { m: 'weatherStation',   dx:  155, dy:  -20, k: 0.9 },
    { m: 'signpost',         dx:  -30, dy:   62, k: 1.2, hero: true },
    { m: 'houseCluster',     dx: -175, dy:   62, k: 0.8 },
  ]},
  24: { name: 'Snow dynamics', items: [
    { m: 'snowPit',          dx:  -65, dy:   32, k: 1.3, hero: true },
    { m: 'snowStake',        dx:   62, dy:  -20, k: 1.2 },
    { m: 'cornice',          dx: -185, dy: -110, k: 1.2 },
    { m: 'avalancheTrack',   dx:  125, dy: -120, k: 1.1 },
    { m: 'person',           dx:   20, dy:   84, k: 1.0 },
    { m: 'weatherStation',   dx:  185, dy:   62, k: 0.9 },
    { m: 'icicles',          dx: -120, dy:   92, k: 1.0 },
  ]},
  25: { name: 'Permafrost', items: [
    /* the rock glacier is the hero, on the talus below the snow and clear of the ice */
    { m: 'rockGlacier',      dx:  140, dy:   50, k: 0.85, hero: true },
    { m: 'thawSlump',        dx: -120, dy:   90, k: 0.95 },
    { m: 'boreholeRig',      dx:   40, dy:  150, k: 0.9 },
    { m: 'permafrostBorehole', dx: 40, dy:  165, k: 0.8 },
    { m: 'frostCrackedRock', dx: -40, dy:  210, k: 0.9 },
    { m: 'icicles',          dx: -150, dy:  -40, k: 0.8 },
  ]},
};
